
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1
{

using System;
    using System.Collections.Generic;
    
public partial class NaryadService
{

    public int id { get; set; }

    public int ServiceID { get; set; }

    public int NaryadID { get; set; }

    public decimal Price { get; set; }

    public int Count { get; set; }



    public virtual Service Service { get; set; }

}

}
