
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1
{

using System;
    using System.Collections.Generic;
    
public partial class ProviderOrderProduct
{

    public int Id { get; set; }

    public int ProductId { get; set; }

    public int ProviderOrderId { get; set; }

    public decimal Price { get; set; }

    public int Count { get; set; }



    public virtual Product Product { get; set; }

    public virtual ProviderOrder ProviderOrder { get; set; }

}

}
