
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1
{

using System;
    using System.Collections.Generic;
    
public partial class ProviderOrder
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProviderOrder()
    {

        this.ProviderOrderProduct = new HashSet<ProviderOrderProduct>();

    }


    public int Id { get; set; }

    public int ProviderId { get; set; }

    public int Num { get; set; }

    public System.DateTime Date { get; set; }

    public decimal Total { get; set; }



    public virtual Provider Provider { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProviderOrderProduct> ProviderOrderProduct { get; set; }

}

}
