
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1
{

using System;
    using System.Collections.Generic;
    
public partial class RegistrService
{

    public int id { get; set; }

    public int ServiceDiscountID { get; set; }

    public int PersonID { get; set; }

    public decimal Total { get; set; }

    public System.DateTime TimeStart { get; set; }

    public System.DateTime TimeEnd { get; set; }



    public virtual ServiceDiscount ServiceDiscount { get; set; }

}

}
