
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1
{

using System;
    using System.Collections.Generic;
    
public partial class SysPaym
{

    public int Id { get; set; }

    public decimal Total { get; set; }

    public int PersonPaymentId { get; set; }

    public decimal encouaragment { get; set; }

    public decimal Punishment { get; set; }



    public virtual PersonPayment PersonPayment { get; set; }

}

}
