//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManService
    {
        public int id { get; set; }
        public int Serviceid { get; set; }
        public int Usermanid { get; set; }
    
        public virtual Serivce Serivce { get; set; }
        public virtual Userman Userman { get; set; }
    }
}
